# Series

In [1]:
# %pip install pandas
import pandas as pd
seriesa = pd.Series( [10, 20, 30] )
sorted(seriesa)

[10, 20, 30]

In [2]:
seriesa[0]

np.int64(10)

In [3]:
seriesa.loc(0)

In [4]:
seriesa + seriesa

0    20
1    40
2    60
dtype: int64

In [5]:
list(zip(seriesa))

[(10,), (20,), (30,)]

# Dataframe

In [6]:
data = pd.DataFrame({
    "Product": ["Pearls", "Cup", "Tea"],
    "Price": [100, 25, 300],
})

In [7]:
# Unsure of usage data.query("Product = Pearls")
data.shape

(3, 2)

In [8]:
data.columns

Index(['Product', 'Price'], dtype='str')

In [9]:
data.iloc[2:3]

  Product  Price
2     Tea    300

In [10]:
data = {
    "Serial No.": [1, 2, 3, 4, 5],
    "gre score": [337, 324, 316, 322, 314],
    "toefl score": [118, 107, 104, 110, 103],
}
df = pd.DataFrame(data).set_index("Serial No.")

In [11]:
df[(df['toefl score'] > 105) & (df['toefl score'] < 115)]

            gre score  toefl score
Serial No.
2                 324          107
4                 322          110

In [12]:
type(df)
df.shape

(5, 2)

In [16]:
df[df['toefl score'].gt(105) & df['toefl score'].lt(115)]

            gre score  toefl score
Serial No.
2                 324          107
4                 322          110

In [17]:
import pandas as pd
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj1 = pd.Series(sdata)
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj2 = pd.Series(sdata, index=states)
obj3 = pd.isnull(obj2)

In [22]:
obj2['California']

np.float64(nan)

In [24]:
import numpy as np
df = pd.DataFrame(
    np.arange(16).reshape((4, 4)),
    index=["Ohio", "Colorado", "Utah", "New York"],
    columns=["one", "two", "three", "four"],
)

In [29]:
df.drop('two', axis = 1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [37]:
import pandas as pd
s1 = pd.Series({1: 'Alice', 2: 'Jack', 3: 'Molly'})
s2 = pd.Series({'Alice': 1, 'Jack': 2, 'Molly': 3})

In [33]:
#df.rename(mapper = lambda x: x.upper(), axis = 1)

In [34]:
import pandas as pd
d = {'1': 'Alice','2': 'Bob','3': 'Rita','4': 'Molly','5': 'Ryan'}
S = pd.Series(d)

In [36]:
S.iloc[0:3]

1    Alice
2      Bob
3     Rita
dtype: str